/* $Id: test_names.hxx,v 1.33 2002/08/20 15:10:55 jenglund Exp $ */
/*******************************************************************/
/*    Copyright (c) 1989-2020 by Spatial Corp.                     */
/*    All rights reserved.                                         */
/*    Protected by U.S. Patents 5,257,205; 5,351,196; 6,369,815;   */
/*                              5,982,378; 6,462,738; 6,941,251    */
/*    Protected by European Patents 0503642; 69220263.3            */
/*    Protected by Hong Kong Patent 1008101A                       */
/*******************************************************************/

// Skinning
#define SKIN_YO_YO                         "skin_yo_yo"                            , FAST,   "20000907"
#define SKIN_STAR_SEED1                    "skin_star_seed1"                       , FAST,   "20000907"
#define SKIN_STAR_SEED2                    "skin_star_seed2"                       , FAST,   "20000907"
#define SKIN_RULED_STAR_SEED               "skin_ruled_star_seed"                  , FAST,   "20000907"
#define SKIN_STAR_DRUM                     "skin_star_drum"                        , FAST,   "20000907"
#define SKIN_TOP                           "skin_top"                              , FAST,   "20000907"
#define SKIN_SEED_POD                      "skin_seed_pod"                         , FAST,   "20000907"
#define SKIN_BOTTLE                        "skin_bottle"                           , FAST,   "20000907"
#define SKIN_VASE                          "skin_vase"                             , FAST,   "20000907"
#define SKIN_WORM                          "skin_worm"                             , FAST,   "20000907"
#define SKIN_NOSE_STAR                     "skin_nose_star"                        , FAST,   "20000907"
#define SKIN_CURVED_STAR_BODY              "skin_curved_star_body"                 , FAST,   "20000907"
#define SKIN_BAD_STIRRUP                   "skin_bad_stirrup"                      , FAST,   "20000907"
#define SKIN_GOOD_STIRRUP                  "skin_good_stirrup"                     , FAST,   "20000907"
#define SKIN_LENSE_BODY                    "skin_lense_body"                       , FAST,   "20000907"
#define SKIN_LOFT_MOON_TUB                 "skin_loft_moon_tub"                    , FAST,   "20000907"
#define SKIN_BALLOON                       "skin_balloon"                          , FAST,   "20000907"
#define SKIN_TWISTED_STAR_SEED             "skin_twisted_star_seed"                , FAST,   "20000907"
#define SKIN_BALLOON_ON_CYLINDRICAL_FACE1  "skin_balloon_on_cylindrical_face1"     , FAST,   "20000907"
#define SKIN_BALLOON_ON_CYLINDRICAL_FACE2  "skin_balloon_on_cylindrical_face2"     , FAST,   "20000907"
#define SKIN_ROBOT_TOOTH                   "skin_robot_tooth"                      , FAST,   "20000907"
#define SKIN_BAD_SQUARE_EGG                "skin_bad_square_egg"                   , FAST,   "20000907"
#define SKIN_GOOD_SQUARE_EGG               "skin_good_square_egg"                  , FAST,   "20000907"
#define SKIN_DENTED_DOUGHNUT               "skin_dented_doughnut"                  , FAST,   "20000907"
#define SKIN_BULGING_DOUGHNUT              "skin_bulging_doughnut"                 , FAST,   "20000907"
#define SKIN_FLOWER                        "skin_flower"                           , FAST,   "20000907"

// Patterns
#define PAT_ABL_CHAMFER_EDGES              "pat_abl_chamfer_edges"                 , SMOKE,  "20021010"
#define PAT_ABL_ROUND_EDGES                "pat_abl_round_edges"                   , SMOKE,  "20021010"
#define PAT_ADD_KEEP                       "pat_add_keep"                          , SMOKE,  "20000918"
#define PAT_ADD_SCALE                      "pat_add_scale"                         , SMOKE,  "20000918"
#define PAT_AXES1                          "pat_axes1"                             , SMOKE,  "20000918"
#define PAT_AXES2                          "pat_axes2"                             , SMOKE,  "20000918"
#define PAT_AXES3                          "pat_axes3"                             , SMOKE,  "20000918"
#define PAT_AXES4                          "pat_axes4"                             , SMOKE,  "20000918"
#define PAT_BLEND_CHAMFER_VERTICES         "pat_blend_chamfer_vertices"            , SMOKE,  "20021010"
#define PAT_BLEND_CONST_CHAMFERS           "pat_blend_const_chamfers"              , SMOKE,  "20021010"
#define PAT_BLEND_CONST_ROUNDS             "pat_blend_const_rounds"                , SMOKE,  "20021010"
#define PAT_BLEND_TWICE_FIX_ONCE           "pat_blend_twice_fix_once"              , SMOKE,  "20021010"
#define PAT_BOOL_DIE                       "pat_bool_die"                          , SMOKE,  "20020802"
#define PAT_BOOL_INTERSECT                 "pat_bool_intersect"                    , SMOKE,  "20020802"
#define PAT_BOOL_LOOPS                     "pat_bool_loops"                        , SMOKE,  "20020802"
#define PAT_BOOL_MERGE                     "pat_bool_merge"                        , SMOKE,  "20020930"
#define PAT_BOOL_SHELLS                    "pat_bool_shells"                       , SMOKE,  "20020802"
#define PAT_BOOL_SUBTRACT                  "pat_bool_subtract"                     , SMOKE,  "20020802"
#define PAT_BOOL_UNITE                     "pat_bool_unite"                        , SMOKE,  "20020802"
#define PAT_BUMP_CYLINDER                  "pat_bump_cylinder"                     , SMOKE,  "20000918"
#define PAT_BUMP_SPHERE                    "pat_bump_sphere"                       , SMOKE,  "20000918"
#define PAT_BUMP_TORUS                     "pat_bump_torus"                        , SMOKE,  "20000918"
#define PAT_CAT_LINEAR_CIRCULAR            "pat_cat_linear_circular"               , FAST,   "20000918"
#define PAT_CAT_POLAR_LINEAR               "pat_cat_polar_linear"                  , SMOKE,  "20000918"
#define PAT_CHINESE                        "pat_chinese"                           , SMOKE,  "20000918"
#define PAT_CIRCULAR                       "pat_circular"                          , SMOKE,  "20000918"
#define PAT_CIRCULAR_ARC                   "pat_circular_arc"                      , FAST,   "20000918"
#define PAT_CIRCULAR_NOT_ROTATE            "pat_circular_not_rotate"               , SMOKE,  "20000918"
#define PAT_COEDGE                         "pat_coedge"                            , SMOKE,  "20000918"
#define PAT_COMPOSE_CIRCULAR               "pat_compose_circular"                  , FAST,   "20000918"
#define PAT_COMPOSE_LINEAR                 "pat_compose_linear"                    , SMOKE,  "20000918"
#define PAT_COMPOSE_LISTS                  "pat_compose_lists"                     , SMOKE,  "20000918"
#define PAT_COMPOSE_POLAR                  "pat_compose_polar"                     , SMOKE,  "20000918"
#define PAT_COMPOSE_REFLECT_CIRCULAR       "pat_compose_reflect_circular"          , FAST,   "20000918"
#define PAT_CURVE                          "pat_curve"                             , SMOKE,  "20000918"
#define PAT_CURVE_ON_ENDPOINTS             "pat_curve_on_endpoints"                , SMOKE,  "20000918"
#define PAT_CURVE_USE_RAIL                 "pat_curve_use_rail"                    , FAST,   "20000918"
#define PAT_CYLINDRICAL                    "pat_cylindrical"                       , FAST,   "20000918"
#define PAT_CYLINDRICAL_ALT                "pat_cylindrical_alt"                   , SMOKE,  "20000918"
#define PAT_CYLINDRICAL_FACE               "pat_cylindrical_face"                  , SMOKE,  "20000918"
#define PAT_DE_FIG01                       "pat_de_fig1"                           , SMOKE,  "20000918"
#define PAT_DE_FIG02                       "pat_de_fig2"                           , SMOKE,  "20000918"
#define PAT_DE_FIG03                       "pat_de_fig3"                           , SMOKE,  "20000918"
#define PAT_DE_FIG04                       "pat_de_fig4"                           , SMOKE,  "20000918"
#define PAT_DE_FIG05                       "pat_de_fig5"                           , SMOKE,  "20000918"
#define PAT_DE_FIG06                       "pat_de_fig6"                           , SMOKE,  "20000918"
#define PAT_DE_FIG07                       "pat_de_fig7"                           , FAST,   "20000918"
#define PAT_DE_FIG08                       "pat_de_fig8"                           , SMOKE,  "20000918"
#define PAT_DE_FIG09                       "pat_de_fig9"                           , SMOKE,  "20000918"
#define PAT_DE_FIG10                       "pat_de_fig10"                          , SMOKE,  "20000918"
#define PAT_DE_FIG11                       "pat_de_fig11"                          , SMOKE,  "20000918"
#define PAT_DE_FIG12                       "pat_de_fig12"                          , SMOKE,  "20000918"
#define PAT_DE_FIG13                       "pat_de_fig13"                          , SMOKE,  "20000918"
#define PAT_DE_CHANGE_ALL_BUMPS            "pat_de_change_all_bumps"               , SMOKE,  "20000918"
#define PAT_DE_CHANGE_ALL_LOOPS            "pat_de_change_all_loops"               , SMOKE,  "20000918"
#define PAT_DE_CHANGE_ALL_LUMPS            "pat_de_change_all_lumps"               , SMOKE,  "20000918"
#define PAT_DE_CHANGE_ALL_SHELLS           "pat_de_change_all_shells"              , SMOKE,  "20000918"
#define PAT_EDGE                           "pat_edge"                              , SMOKE,  "20000918"
#define PAT_EDGE_FACE                      "pat_edge_face"                         , SMOKE,  "20000918"
#define PAT_EDGE_ON_ENDPOINTS              "pat_edge_on_endpoints"                 , SMOKE,  "20000918"
#define PAT_EDGE_USE_RAIL                  "pat_edge_use_rail"                     , FAST,   "20000918"
#define PAT_ELLIPTICAL                     "pat_elliptical"                        , SMOKE,  "20000918"
#define PAT_ELLIPTICAL_ARC                 "pat_elliptical_arc"                    , FAST,   "20000918"
#define PAT_ELLIPTICAL_NOT_ROTATE          "pat_elliptical_not_rotate"             , SMOKE,  "20000918"
#define PAT_FACE                           "pat_face"                              , SMOKE,  "20000918"
#define PAT_FACE_ON_BOUNDARY               "pat_face_on_boundary"                  , SMOKE,  "20000918"
#define PAT_FACE_USE_NORMAL                "pat_face_use_normal"                   , SMOKE,  "20000918"
#define PAT_FACES_CIRCULAR_ON_EDGE1        "pat_faces_circular_on_edge1"           , SMOKE,  "20030312"
#define PAT_FACES_CIRCULAR_ON_EDGE2        "pat_faces_circular_on_edge2"           , SMOKE,  "20030312"
#define PAT_FACES_CIRCULAR_ON_EDGES        "pat_faces_circular_on_edges"           , SMOKE,  "20030312"
#define PAT_FACES_CIRCULAR_ON_EDGES2       "pat_faces_circular_on_edges2"          , SMOKE,  "20030312"
#define PAT_FACES_CIRCULAR_ON_FACES        "pat_faces_circular_on_faces"           , SMOKE,  "20030312"
#define PAT_FACES_CIRCULAR_ON_FACES2       "pat_faces_circular_on_faces2"          , SMOKE,  "20030312"
#define PAT_FACES_LINEAR_ON_EDGE           "pat_faces_linear_on_edge"              , SMOKE,  "20030312"
#define PAT_FACES_LINEAR_ON_EDGES          "pat_faces_linear_on_edges"             , SMOKE,  "20030312"
#define PAT_FACES_LINEAR_ON_FACES          "pat_faces_linear_on_faces"             , SMOKE,  "20030312"
#define PAT_FIX_BUMPS                      "pat_fix_bumps"                         , SMOKE,  "20020610"
#define PAT_FIX_CYLINDRICAL                "pat_fix_cylindrical"                   , SMOKE,  "20020610"
#define PAT_FIX_LINEAR                     "pat_fix_linear"                        , SMOKE,  "20020610"
#define PAT_FIX_LOOPS                      "pat_fix_loops"                         , SMOKE,  "20020610"
#define PAT_FIX_SHELLS                     "pat_fix_shells"                        , SMOKE,  "20020610"
#define PAT_FIX_SPHERICAL                  "pat_fix_spherical"                     , SMOKE,  "20020610"
#define PAT_FROM_LAWS                      "pat_from_laws"                         , FAST,   "20000918"
#define PAT_FROM_LIST                      "pat_from_list"                         , SMOKE,  "20000918"
#define PAT_FROM_TRANSF_LIST               "pat_from_transf_list"                  , SMOKE,  "20000918"
#define PAT_HEX_2D                         "pat_hex_2d"                            , FAST,   "20000918"
#define PAT_HEX_3D                         "pat_hex_3d"                            , SMOKE,  "20000918"
#define PAT_HEX_CYLINDRICAL                "pat_hex_cylindrical"                   , FAST,   "20000918"
#define PAT_HEX_CYLINDRICAL_FACE           "pat_hex_cylindrical_face"              , SMOKE,  "20000918"
#define PAT_KEEP_ALT                       "pat_keep_alt"                          , SMOKE,  "20000918"
#define PAT_KEEP_ALT_MERGE                 "pat_keep_alt_merge"                    , SMOKE,  "20000918"
#define PAT_KEEP_PERIODIC                  "pat_keep_periodic"                     , SMOKE,  "20000918"
#define PAT_KEEP_PERIODIC_MERGE            "pat_keep_periodic_merge"               , FAST,   "20000918"
#define PAT_KEEP_RANDOM                    "pat_keep_random"                       , SMOKE,  "20000918"
#define PAT_KEEP_RANDOM_MERGE              "pat_keep_random_merge"                 , SMOKE,  "20000918"
#define PAT_LINEAR_1D                      "pat_linear_1d"                         , SMOKE,  "20000918"
#define PAT_LINEAR_2D                      "pat_linear_2d"                         , SMOKE,  "20000918"
#define PAT_LINEAR_3D                      "pat_linear_3d"                         , FAST,   "20000918"
#define PAT_LINEAR_STAGGERED               "pat_linear_staggered"                  , SMOKE,  "20000918"
#define PAT_MERGE_BUMPS                    "pat_merge_bumps"                       , SMOKE,  "20030114"
#define PAT_MERGE_HOLES                    "pat_merge_holes"                       , SMOKE,  "20030114"
#define PAT_MERGE_SHEET_BUMPS              "pat_merge_sheet_bumps"                 , SMOKE,  "20030114"
#define PAT_MIRROR                         "pat_mirror"                            , FAST,   "20000918"
#define PAT_MIRROR_MIRROR_WIGGLE           "pat_mirror_mirror_wiggle"              , FAST,   "20000918"
#define PAT_MIRROR_SCALE_BUMPS             "pat_mirror_scale_bumps"                , FAST,   "20000918"
#define PAT_MOVE_ELEMENT                   "pat_move_element"                      , SMOKE,  "20000918"
#define PAT_MOVE_ROOT_CYL                  "pat_move_root_cyl"                     , SMOKE,  "20000918"
#define PAT_MOVE_ROOT_FACE                 "pat_move_root_face"                    , FAST,   "20000918"
#define PAT_MOVE_ROOT_LOOP                 "pat_move_root_loop"                    , SMOKE,  "20000918"
#define PAT_MOVE_ROOT_LUMP                 "pat_move_root_lump"                    , SMOKE,  "20000918"
#define PAT_MOVE_ROOT_SHELL                "pat_move_root_shell"                   , SMOKE,  "20000918"
#define PAT_NONUNIFORM_SCALE_ALT           "pat_nonuniform_scale_alt"              , SMOKE,  "20000918"
#define PAT_NONUNIFORM_SCALE_BUMPS         "pat_nonuniform_scale_bumps"            , SMOKE,  "20000918"
#define PAT_NONUNIFORM_SCALE_CYL_BUMPS     "pat_nonuniform_scale_cyl_bumps"        , SMOKE,  "20000918"
#define PAT_NONUNIFORM_SCALE_LAW           "pat_nonuniform_scale_law"              , SMOKE,  "20000918"
#define PAT_NONUNIFORM_SCALE_LOOPS         "pat_nonuniform_scale_loops"            , SMOKE,  "20000918"
#define PAT_NONUNIFORM_SCALE_LUMPS         "pat_nonuniform_scale_lumps"            , SMOKE,  "20000918"
#define PAT_NONUNIFORM_SCALE_MERGE_HOLES   "pat_nonuniform_scale_merge_holes"      , SMOKE,  "20000918"
#define PAT_NONUNIFORM_SCALE_MERGE_LUMPS   "pat_nonuniform_scale_merge_lumps"      , SMOKE,  "20000918"
#define PAT_NONUNIFORM_SCALE_PERIODIC      "pat_nonuniform_scale_periodic"         , SMOKE,  "20000918"
#define PAT_NONUNIFORM_SCALE_RANDOM        "pat_nonuniform_scale_random"           , SMOKE,  "20000918"
#define PAT_NONUNIFORM_SCALE_SHELLS        "pat_nonuniform_scale_shells"           , SMOKE,  "20000918"
#define PAT_NONUNIFORM_SCALE_SPHERE_BUMPS  "pat_nonuniform_scale_sphere_bumps"     , SMOKE,  "20000918"
#define PAT_NONUNIFORM_SCALE_TBUMPS        "pat_nonuniform_scale_tbumps"           , SMOKE,  "20000918"
#define PAT_NONUNIFORM_SCALE_TORUS         "pat_nonuniform_scale_torus"            , SMOKE,  "20000918"
#define PAT_OFFSET_BODY_BUMPS              "pat_offset_body_bumps"                 , SMOKE,  "20000918"
#define PAT_OFFSET_BODY_HOLES              "pat_offset_body_holes"                 , SMOKE,  "20000918"
#define PAT_OFFSET_BODY_LUMPS              "pat_offset_body_lumps"                 , SMOKE,  "20000918"
#define PAT_OFFSET_BODY_SHELLS             "pat_offset_body_shells"                , SMOKE,  "20000918"
#define PAT_OFFSET_DOUBLE_SPHERE           "pat_offset_double_sphere"              , SMOKE,  "20000918"
#define PAT_OFFSET_FACES_BUMPS             "pat_offset_faces_bumps"                , SMOKE,  "20000918"
#define PAT_OFFSET_FACES_HOLES             "pat_offset_faces_holes"                , SMOKE,  "20000918"
#define PAT_OFFSET_FACES_LUMPS             "pat_offset_faces_lumps"                , SMOKE,  "20000918"
#define PAT_OFFSET_FACES_SHELLS            "pat_offset_faces_shells"               , SMOKE,  "20000918"
#define PAT_OFFSET_LOSE_BLEND_LUMPS        "pat_offset_lose_blend_lumps"           , SMOKE,  "20000918"
#define PAT_OFFSET_LOSE_BLEND_BUMPS        "pat_offset_lose_blend_bumps"           , SMOKE,  "20000918"
#define PAT_OFFSET_LOSE_BLEND_HOLES        "pat_offset_lose_blend_holes"           , SMOKE,  "20000918"
#define PAT_OFFSET_LOSE_BLEND_SHELLS       "pat_offset_lose_blend_shells"          , SMOKE,  "20000918"
#define PAT_OFFSET_LOSE_CHAMFER_LUMPS      "pat_offset_lose_chamfer_lumps"         , SMOKE,  "20000918"
#define PAT_OFFSET_LOSE_CHAMFER_BUMPS      "pat_offset_lose_chamfer_bumps"         , SMOKE,  "20000918"
#define PAT_OFFSET_LOSE_CHAMFER_HOLES      "pat_offset_lose_chamfer_holes"         , SMOKE,  "20000918"
#define PAT_OFFSET_LOSE_CHAMFER_SHELLS     "pat_offset_lose_chamfer_shells"        , SMOKE,  "20000918"
#define PAT_OFFSET_SPEC_FACES_BUMPS        "pat_offset_spec_faces_bumps"           , SMOKE,  "20000918"
#define PAT_OFFSET_SPEC_FACES_HOLES        "pat_offset_spec_faces_holes"           , SMOKE,  "20000918"
#define PAT_OFFSET_SPEC_FACES_LUMPS        "pat_offset_spec_faces_lumps"           , SMOKE,  "20000918"
#define PAT_OFFSET_SPEC_FACES_SHELLS       "pat_offset_spec_faces_shells"          , SMOKE,  "20000918"
#define PAT_OFFSET_SPHERE_BUMPS            "pat_offset_sphere_bumps"               , SMOKE,  "20000918"
#define PAT_POLAR_GRID                     "pat_polar_grid"                        , SMOKE,  "20000918"
#define PAT_POLAR_GRID_ARC                 "pat_polar_grid_arc"                    , SMOKE,  "20000918"
#define PAT_POLAR_GRID_ELLIPSE             "pat_polar_grid_ellipse"                , FAST,   "20000918"
#define PAT_POLAR_GRID_HEX                 "pat_polar_grid_hex"                    , SMOKE,  "20000918"
#define PAT_POLAR_GRID_NOT_ROTATE          "pat_polar_grid_not_rotate"             , SMOKE,  "20000918"
#define PAT_RADIAL                         "pat_radial"                            , SMOKE,  "20000918"
#define PAT_RADIAL_ARC                     "pat_radial_arc"                        , SMOKE,  "20000918"
#define PAT_RADIAL_ELLIPSE                 "pat_radial_ellipse"                    , FAST,   "20000918"
#define PAT_RADIAL_NOT_ROTATE              "pat_radial_not_rotate"                 , SMOKE,  "20000918"
#define PAT_RANDOM_BOX                     "pat_random_box"                        , FAST,   "20000918"
#define PAT_RANDOM_LINE                    "pat_random_line"                       , SMOKE,  "20000918"
#define PAT_RANDOM_OFFSET                  "pat_random_offset"                     , SMOKE,  "20000918"
#define PAT_RANDOM_ORIENT_AXIAL            "pat_random_orient_axial"               , SMOKE,  "20000918" 
#define PAT_RANDOM_ORIENT_TILT             "pat_random_orient_tilt"                , SMOKE,  "20000918" 
#define PAT_RANDOM_PLANE                   "pat_random_plane"                      , SMOKE,  "20000918"
#define PAT_RANDOM_SPHERE                  "pat_random_sphere"                     , SMOKE,  "20000918"
#define PAT_REFLECT_CIRCULAR               "pat_reflect_circular"                  , SMOKE,  "20000918"
#define PAT_REMOVE_ELEMENTS                "pat_remove_elements"                   , SMOKE,  "20000918"
#define PAT_REMOVE_FIRST_TWO_BUMPS         "pat_remove_first_two_bumps"            , FAST,   "20000918"
#define PAT_REMOVE_PAT_BUMP                "pat_remove_pat_bump"                   , SMOKE,  "20000918"
#define PAT_REMOVE_PAT_LOOP                "pat_remove_pat_loop"                   , SMOKE,  "20000918"
#define PAT_REMOVE_PAT_LUMP                "pat_remove_pat_lump"                   , SMOKE,  "20000918"
#define PAT_REMOVE_PAT_SHELL               "pat_remove_pat_shell"                  , SMOKE,  "20000918"
#define PAT_REMOVE_ROOT_DBL_TORUS          "pat_remove_root_dbl_torus"             , SMOKE,  "20000918"
#define PAT_REMOVE_ROOT_DOLL               "pat_remove_root_doll"                  , SMOKE,  "20000918"
#define PAT_REMOVE_ROOT_FACE               "pat_remove_root_face"                  , SMOKE,  "20000918"
#define PAT_REMOVE_ROOT_HANDLE             "pat_remove_root_handle"                , SMOKE,  "20000918"
#define PAT_REMOVE_ROOT_LOOP               "pat_remove_root_loop"                  , SMOKE,  "20000918"
#define PAT_REMOVE_ROOT_LUMP               "pat_remove_root_lump"                  , SMOKE,  "20000918"
#define PAT_REMOVE_ROOT_SHELL              "pat_remove_root_shell"                 , SMOKE,  "20000918"
#define PAT_REMOVE_ROOT_SWP_HOLE           "pat_remove_root_swp_hole"              , SMOKE,  "20000918"
#define PAT_REMOVE_ROOT_XHOLE              "pat_remove_root_xhole"                 , SMOKE,  "20000918"
#define PAT_RESTORE_ELEMENT                "pat_restore_element"                   , SMOKE,  "20000918"
#define PAT_SCALE_ALT                      "pat_scale_alt"                         , SMOKE,  "20000918"
#define PAT_SCALE_ALT_MERGE                "pat_scale_alt_merge"                   , SMOKE,  "20000918"
#define PAT_SCALE_ELEMENT                  "pat_scale_element"                     , SMOKE,  "20000918"
#define PAT_SCALE_LINEAR                   "pat_scale_linear"                      , SMOKE,  "20000918"
#define PAT_SCALE_LINEAR_MERGE             "pat_scale_linear_merge"                , FAST,   "20000918"
#define PAT_SCALE_PERIODIC                 "pat_scale_periodic"                    , SMOKE,  "20000918"
#define PAT_SCALE_PERIODIC_MERGE           "pat_scale_periodic_merge"              , SMOKE,  "20000918"
#define PAT_SCALE_RANDOM                   "pat_scale_random"                      , SMOKE,  "20000918"
#define PAT_SCALE_RANDOM_MERGE             "pat_scale_random_merge"                , SMOKE,  "20000918"
#define PAT_SCALE_ROOT_FACE                "pat_scale_root_face"                   , FAST ,  "20000918"
#define PAT_SCALE_ROOT_LOOP                "pat_scale_root_loop"                   , SMOKE,  "20000918"
#define PAT_SCALE_ROOT_LUMP                "pat_scale_root_lump"                   , SMOKE,  "20000918"
#define PAT_SCALE_ROOT_SHELL               "pat_scale_root_shell"                  , SMOKE,  "20000918"
#define PAT_SEMAPHORE                      "pat_semaphore"                         , FAST,   "20000918"
#define PAT_SHELL_BUMPS                    "pat_shell_bumps"                       , SMOKE,  "20000918"
#define PAT_SHELL_DOUBLE_SPHERE            "pat_shell_double_sphere"               , SMOKE,  "20000918"
#define PAT_SHELL_LOSE_BLEND_LUMPS         "pat_shell_lose_blend_lumps"            , SMOKE,  "20000918"
#define PAT_SHELL_LOSE_BLEND_BUMPS         "pat_shell_lose_blend_bumps"            , SMOKE,  "20000918"
#define PAT_SHELL_LOSE_BLEND_HOLES         "pat_shell_lose_blend_holes"            , SMOKE,  "20000918"
#define PAT_SHELL_LOSE_CHAMFER_LUMPS       "pat_shell_lose_chamfer_lumps"          , SMOKE,  "20000918"
#define PAT_SHELL_LOSE_CHAMFER_BUMPS       "pat_shell_lose_chamfer_bumps"          , SMOKE,  "20000918"
#define PAT_SHELL_LOSE_CHAMFER_HOLES       "pat_shell_lose_chamfer_holes"          , SMOKE,  "20000918"
#define PAT_SHELL_LUMPS                    "pat_shell_lumps"                       , SMOKE,  "20000918"
#define PAT_SHELL_OPEN_BUMPS               "pat_shell_open_bumps"                  , SMOKE,  "20000918"
#define PAT_SHELL_OPEN_LUMPS               "pat_shell_open_lumps"                  , SMOKE,  "20000918"
#define PAT_SHELL_SHEET_THICKEN            "pat_shell_sheet_thicken"               , SMOKE,  "20000918"
#define PAT_SHELL_SPEC_BUMPS               "pat_shell_spec_bumps"                  , SMOKE,  "20000918"
#define PAT_SHELL_SPEC_LUMPS               "pat_shell_spec_lumps"                  , SMOKE,  "20000918"
#define PAT_SHELL_SPHERE_BUMPS             "pat_shell_sphere_bumps"                , SMOKE,  "20000918"
#define PAT_SNOWFLAKES                     "pat_snowflakes"                        , FAST,   "20000918"
#define PAT_SPHERICAL                      "pat_spherical"                         , FAST,   "20000918"
#define PAT_SPHERICAL_SPACING              "pat_spherical_spacing"                 , SMOKE,  "20000918"
#define PAT_SURFACE                        "pat_surface"                           , SMOKE,  "20000918"
#define PAT_SURFACE_KEEP                   "pat_surface_keep"                      , SMOKE,  "20000918"
#define PAT_TAPER                          "pat_taper"                             , SMOKE,  "20020930"
#define PAT_TAPER_EDGE                     "pat_taper_edge"                        , SMOKE,  "20020930"
#define PAT_TAPER_SHADOW1                  "pat_taper_shadow1"                     , SMOKE,  "20020930"
#define PAT_TAPER_SHADOW2                  "pat_taper_shadow2"                     , SMOKE,  "20020930"
#define PAT_TAPER_SHADOW3                  "pat_taper_shadow3"                     , SMOKE,  "20020930"

// Boolean
#define BOOL_CHOP						   "bool_chop"							   , ALL , "20140826"
#define BOOL_INTERSECTION				   "bool_intersection"					   , ALL , "20140826"
#define BOOL_MAKE_SHADOW				   "bool_make_shadow"					   , ALL , "20140826"
#define BOOL_PROJECT_EDGE_TO_FACE		   "bool_project_edge_to_face"			   , ALL , "20140826"
#define BOOL_PROJECT_WIRE_TO_BODY		   "bool_project_wire_to_body"			   , ALL , "20140826"
#define BOOL_SPLIT_WIRE_EDGE			   "bool_split_wire_edge"				   , ALL , "20140826"
#define BOOL_SUBDIVIDE_FACE				   "bool_subdivide_face"				   , ALL , "20140826"
#define BOOL_SUBTRACTION				   "bool_subtraction"					   , ALL , "20140826"
#define BOOL_UNITE						   "bool_unite"							   , ALL , "20140826"

// Blending
#define BLEND_RADIUS_TRANSITION1           "blend_radius_transition1"              , SMOKE, "20000907"
#define BLEND_RADIUS_TRANSITION2           "blend_radius_transition2"              , SMOKE, "20010221"
#define BLEND_MITRE_AND_CAP                "blend_mitre_and_cap"                   , ALL,   "20000915"
#define BLEND_MIXED_CONVEXITY              "blend_mixed_convexity"                 , SMOKE, "20000922"
#define BLEND_CIRCUS                       "blend_circus"                          , ALL,   "20000925"
#define BLEND_DIAMANTE                     "blend_diamante"                        , FAST,  "20000925"
#define BLEND_PENCIL                       "blend_pencil"                          , FAST,  "20000925"
#define BLEND_SMOOTH_PENCIL                "blend_smooth_pencil"                   , FAST,  "20001016"
#define BLEND_TAPERING                     "blend_tapering"                        , SMOKE, "20000926"
#define BLEND_TAPERING2                    "blend_tapering2"                       , SMOKE, "20000926"
#define BLEND_TAPERING3                    "blend_tapering3"                       , FAST,  "20001109"
#define BLEND_WIGGLE_CONST                 "blend_wiggle_const"                    , ALL,   "20000926"
#define BLEND_WIGGLE_VAR                   "blend_wiggle_var"                      , ALL,   "20000926"
#define BLEND_ELLIPTICAL                   "blend_elliptical"                      , ALL,   "20000927"
#define BLEND_WINE_GLASS                   "blend_wine_glass"                      , SMOKE, "20000927"
#define BLEND_NUMBER_NINE                  "blend_number_nine"                     , SMOKE, "20000928"
#define BLEND_TREASURE_CHEST               "blend_treasure_chest"                  , ALL,   "20000928"
#define BLEND_CLOWN_HAT                    "blend_clown_hat"                       , SMOKE, "20001003"
#define BLEND_TWISTED_BAR                  "blend_twisted_bar"                     , ALL,   "20001003"
#define BLEND_GRIP                         "blend_grip"                            , SMOKE, "20001003"
#define BLEND_DICE                         "blend_dice"                            , SMOKE, "20001004"
#define BLEND_BRITISH_DICE                 "blend_british_dice"                    , ALL,   "20001005"
#define BLEND_SINGLE_STEPS                 "blend_single_steps"                    , SMOKE, "20001005"
#define BLEND_WIRE                         "blend_wire"                            , ALL,   "20001006"
#define BLEND_PLANE                        "blend_plane"                           , ALL,   "20001010"
#define BLEND_CAT_EYE                      "blend_cat_eye"                         , SMOKE, "20001012"
#define BLEND_CHIMNEY                      "blend_chimney"                         , SMOKE, "20001013"
#define BLEND_SPLINE_CHAMFER               "blend_spline_chamfer"                  , SMOKE, "20001016"
#define BLEND_GEMSTONE1                    "blend_gemstone1"                       , FAST,  "20010104"
#define BLEND_GEMSTONE2                    "blend_gemstone2"                       , FAST,  "20010104"
#define BLEND_ROCKY_MOUNTAINS              "blend_rocky_mountains"                 , ALL,   "20010105"
#define BLEND_SIMPLIFY                     "blend_simplify"                        , ALL,   "20010122"
#define BLEND_ANNOTATION                   "blend_annotation"                      , FAST,  "20010125"
#define BLEND_HOLDLINE                     "blend_holdline"                        , SMOKE, "20020928"

// Multithreading
#define MT_EGG_SLICE			            "mt_egg_slice"               		   , SMOKE,	"20140723"
#define PROCESS_MT							"process_mt"						   , SMOKE,	"20140723"
#define MT_WORK_PACKET_QUEUE				"mt_work_packet_queue"				   , SMOKE,	"20140723"

// Stitching
#define STITCH_FULL							"stitch_full"						   , SMOKE, "20150608"

// Incremental Operations
#define INCR_BOOL							"incr_bool"						, SMOKE, "20160405"

// Sweeping
#define SWEEP_PIPE_THROUGH_E_BLOCK			"sweep_pipe_through_e_block"		   , FAST,	"20000925"
#define SWEEP_WEDGE							"sweep_wedge"						   , FAST,	"20000925"
#define SWEEP_DRAFTED_CONE1					"sweep_drafted_cone1"				   , FAST,	"20000925"
#define SWEEP_DRAFTED_BOX_WITH_HOLE			"sweep_drafted_box_with_hole"		   , FAST,	"20000925"
#define SWEEP_DEFORMED_TUBING				"sweep_deformed_tubing"				   , FAST,	"20000925"
#define SWEEP_DEGEN_DRAFT_BOX				"sweep_degen_draft_box"				   , FAST,	"20000925"
#define SWEEP_PIPE_THROUGH_SLOTTED_BLOCK	"sweep_pipe_through_slotted_block"	   , FAST,	"20000925"
#define SWEEP_DRAFTED_BOX_CYL				"sweep_drafted_box_cyl"				   , FAST,	"20000925"
#define SWEEP_TORUS_THROUGH_E_BLOCK			"sweep_torus_through_e_block"		   , FAST,	"20000925"
#define SWEEP_HEART							"sweep_heart"						   , FAST,	"20000925"
#define SWEEP_APPLE_PEEL					"sweep_apple_peel"					   , FAST,	"20000925"
#define SWEEP_RIGID_TUBE1					"sweep_rigid_tube1"					   , FAST,	"20000925"
#define SWEEP_UFO1							"sweep_ufo1"						   , FAST,	"20000925"
#define SWEEP_TWISTED_TUBE					"sweep_twisted_tube"				   , FAST,	"20000925"
#define SWEEP_RIGID_TUBE2					"sweep_rigid_tube2"					   , FAST,	"20000925"
#define SWEEP_SHAFT							"sweep_shaft"						   , FAST,	"20000925"
#define SWEEP_RIGID_PIPE					"sweep_rigid_pipe"					   , FAST,	"20000925"
#define SWEEP_RIGID_PIPE_SHAFT				"sweep_rigid_pipe_shaft"			   , FAST,	"20000925"
#define SWEEP_FIN							"sweep_fin"							   , FAST,	"20000925"
#define SWEEP_ABSTRACT_ART					"sweep_abstract_art"				   , FAST,	"20000925"
#define SWEEP_DRAFTED_TUBE					"sweep_drafted_tube"				   , FAST,	"20000925"
#define SWEEP_DRAFTED_POLYGON1				"sweep_drafted_polygon1"			   , FAST,	"20000925"
#define SWEEP_DRAFTED_POLYGON2				"sweep_drafted_polygon2"			   , FAST,	"20000925"
#define SWEEP_ARCH							"sweep_arch"						   , FAST,	"20000925"
#define SWEEP_DRAFTED_BOX1					"sweep_drafted_box1"				   , FAST,	"20000925"
#define SWEEP_DRAFTED_CONE2					"sweep_drafted_cone2"				   , FAST,	"20000925"
#define SWEEP_ANGLED_POLYGON				"sweep_angled_polygon"				   , FAST,	"20000925"
#define SWEEP_DRAFTED_BOX2					"sweep_drafted_box2"				   , FAST,	"20000925"
#define SWEEP_UFO2							"sweep_ufo2"						   , FAST,	"20000925"
#define SWEEP_OPEN_BOX						"sweep_open_box"					   , SMOKE,	"20010102"


//local ops : begin
#define LOP_CONVERT_PIPES					"lop_convert_pipes"					   , FAST,	"20010125"
#define LOP_EDGE_TAPER_FACES				"lop_taper_faces"					   , FAST,	"20010125"
#define LOP_MOVE_FACES						"lop_move_faces"					   , FAST,	"20010125"
#define LOP_OFFSET_BODY						"lop_offset_body"					   , FAST,	"20010125"
#define LOP_OFFSET_FACES					"lop_offset_faces"					   , FAST,	"20010125"
#define LOP_OFFSET_SPECIFIC					"lop_offset_specific"				   , FAST,	"20010125"
#define LOP_REMOVE_ATTRIBUTES				"lop_remove_attributes"				   , FAST,	"20010125"
#define LOP_ROTATE_FACES					"lop_rotate_faces"					   , FAST,	"20010125"
#define LOP_SHADOW_TAPER_FACES				"lop_shadow_taper_faces"			   , FAST,	"20010125"
#define LOP_SWEEP_MORE						"lop_sweep_more"					   , FAST,	"20010125"
#define LOP_TAPER_FACES						"lop_taper_faces"					   , FAST,	"20010125"
#define LOP_TWEAK_FACES						"lop_tweak_faces"					   , FAST,	"20010125"
#define LOP_TWEAK_FACES_EXTEND				"lop_tweak_faces_extend"			   , FAST,	"20010125"
#define LOP_TWEAK_FACES_INIT				"lop_tweak_faces_init"				   , FAST,	"20010125"
#define LOP_TWEAK_PICK_EDGE_SOLUTION		"lop_tweak_pick_edge_solution"		   , FAST,	"20010125"
#define LOP_TWEAK_QUERY_EDGE_SOLUTIONS		"lop_tweak_query_edge_solutions"	   , FAST,	"20010125"
#define LOP_REMOVE_FACES					"lop_remove_faces"				       , FAST,	"20010226"
#define LOP_OFFSET_FACES_MAKE_SHEET1		"lop_offset_faces_make_sheet1"	       , FAST,	"20010330"
#define LOP_OFFSET_FACES_MAKE_SHEET2		"lop_offset_faces_make_sheet2"	       , FAST,	"20010330"
#define LOP_OFFSET_FACES_MAKE_SHEET3		"lop_offset_faces_make_sheet3"	       , FAST,	"20010330"

#define LOP_OFFSET_TEST01					"lop_offset_test01"					   , FAST,	"20010216"
#define LOP_OFFSET_TEST02					"lop_offset_test02"					   , FAST,	"20010216"

#define LOP_TAPER_BLOCK						"lop_taper_block"					   , ALL,	"20010129"

#define LOP_TAPER_TEST50					"lop_taper_test50"					   , ALL,	"20010129"
#define LOP_TAPER_TEST51					"lop_taper_test51"					   , FAST,	"20010129"
#define LOP_TAPER_TEST52					"lop_taper_test52"					   , ALL,	"20010129"
#define LOP_TAPER_TEST53					"lop_taper_test53"					   , FAST,	"20010129"
#define LOP_TAPER_TEST54					"lop_taper_test54"					   , ALL,	"20010129"
#define LOP_TAPER_TEST55					"lop_taper_test55"					   , ALL,	"20010129"
#define LOP_TAPER_TEST56					"lop_taper_test56"					   , ALL,	"20010129"
#define LOP_TAPER_TEST57					"lop_taper_test57"					   , ALL,	"20010129"
#define LOP_TAPER_TEST58					"lop_taper_test58"					   , ALL,	"20010129"
#define LOP_TAPER_TEST59					"lop_taper_test59"					   , ALL,	"20010129"
#define LOP_TAPER_TEST60					"lop_taper_test60"					   , ALL,	"20010129"

#define LOP_OFFSET_TEST70					"lop_offset_test70"					   , ALL,	"20010129"
#define LOP_OFFSET_TEST71					"lop_offset_test71"					   , ALL,	"20010129"
#define LOP_OFFSET_TEST74					"lop_offset_test74"					   , ALL,	"20010129"
#define LOP_OFFSET_TEST75					"lop_offset_test75"					   , ALL,	"20010129"
#define LOP_OFFSET_TEST76					"lop_offset_test76"					   , ALL,	"20010129"
#define LOP_OFFSET_TEST77					"lop_offset_test77"					   , ALL,	"20010129"
#define LOP_OFFSET_TEST78					"lop_offset_test78"					   , ALL,	"20010129"

#define LOP_OFFSET_TEST80					"lop_offset_test80"					   , ALL,	"20010129"
#define LOP_OFFSET_TEST81					"lop_offset_test81"					   , ALL,	"20010129"
#define LOP_OFFSET_TEST82					"lop_offset_test82"					   , ALL,	"20010129"
#define LOP_OFFSET_TEST83					"lop_offset_test83"					   , ALL,	"20010129"
#define LOP_OFFSET_TEST84					"lop_offset_test84"					   , ALL,	"20010129"
#define LOP_OFFSET_TEST85					"lop_offset_test85"					   , ALL,	"20010129"
// local ops : end


// space warping
#define WARP_BEND_BASIC01					"warp_bend_basic01"					   , FAST,   "20010928"
#define WARP_BEND_BASIC02					"warp_bend_basic02"					   , FAST,   "20010928"
#define WARP_BEND_BASIC03					"warp_bend_basic03"					   , ALL,    "20010928"
#define WARP_BEND_SPIRAL					"warp_bend_spiral"					   , ALL,    "20011001"
#define WARP_BEND_TEST1						"warp_bend_test1"					   , ALL,    "20011001"
#define WARP_BEND_TEST4						"warp_bend_test4"					   , ALL,    "20011002"
#define WARP_BEND_TEST6						"warp_bend_test6"					   , ALL,    "20011002"
#define WARP_STRETCH_UFO					"warp_stretch_ufo"					   , ALL,    "20011002"
#define WARP_RADIATOR						"warp_radiator"						   , ALL,    "20011002"
#define WARP_BEND_SHAFT						"warp_bend_shaft"					   , ALL,    "20011002"
#define WARP_BEND_TO_CURVE_HALF_REEL		"warp_bend_to_curve_half_reel"		   , ALL,    "20011003"
#define WARP_BEND_TO_CURVE_SPLINE			"warp_bend_to_curve_spline"			   , ALL,	 "20011003"
#define WARP_TWIST1							"warp_twist1"						   , ALL,    "20011003"
#define WARP_TWIST2							"warp_twist2"						   , ALL,    "20011004"
#define WARP_TWIST3							"warp_twist3"						   , ALL,    "20011004"
#define WARP_TWIST4							"warp_twist4"						   , ALL,    "20011004"
// space warping:end

// journaling
#define JOURNAL_SWEEPING1					"journal_sweeping1"						, ALL,   "20011114"
#define JOURNAL_3D							"journal_3d"							, ALL,   "20011114"
#define JOURNAL_SKIN_SWEEP_WARP_BOOL		"journal_skin_sweep_warp_bool"			, ALL,   "20011114"
#define JOURNAL_SKIN_SWEEP_WARP_BOOL2		"journal_skin_sweep_warp_bool2"			, ALL,   "20011114"
#define JOURNAL_SKIN_ERROR					"journal_skin_error"					, ALL,   "20011114"
// journaling: end

#define SPLIT_FACE_AT_DISC					"split_face_at_disc"					, ALL,	 "20020730"
#define SPLIT_EDGE_AT_DISC					"split_edge_at_disc"					, ALL,	 "20020730"

// Polyhedral
#define POLY_BOOL_UNITE						"poly_bool_unite"						, FAST,	 "20150616"
#define POLY_BOOL_SUBTRACT					"poly_bool_subtract"					, FAST,	 "20150617"
#define POLY_BOOL_INTERSECT					"poly_bool_intersect"					, FAST,	 "20150617"
#define POLY_PLANAR_SLICE					"poly_planar_slice"						, FAST,  "20150617"
#define POLY_OFFSET_BODY					"poly_offset_body"						, FAST,	 "20150622"
#define POLY_HOLLOW_BODY					"poly_hollow_body"						, FAST,	 "20150622"
#define POLY_CREATE_BODY					"poly_create_body"						, FAST,	 "20150731"
#define POLY_DECIMATE_BODY					"poly_decimate_body"					, FAST,  "20150731"

//================
#define ALL 2
#define SMOKE 1
#define FAST 0
