#ifndef  __MESHGEMS_CADSURF_OLD_NAMES__
#define  __MESHGEMS_CADSURF_OLD_NAMES__

// COPYRIGHT DASSAULT SYSTEMES 2022
//=============================================================================
/**
 * @CAA2Level L0
 * @CAA2Usage U0
 */

#ifndef MESHGEMS_NO_OLD_NAMES

#define distene_blsurf_session_new meshgems_cadsurf_session_new
#define distene_blsurf_session_delete meshgems_cadsurf_session_delete
#define distene_blsurf_set_param meshgems_cadsurf_set_param
#define distene_blsurf_get_param meshgems_cadsurf_get_param
#define distene_blsurf_set_message_callback meshgems_cadsurf_set_message_callback
#define distene_blsurf_set_interrupt_callback meshgems_cadsurf_set_interrupt_callback
#define distene_blsurf_data_set_cad meshgems_cadsurf_data_set_cad
#define distene_blsurf_data_set_dcad meshgems_cadsurf_data_set_dcad
#define distene_blsurf_data_set_sizemap_iso_cad_face meshgems_cadsurf_data_set_sizemap_iso_cad_face
#define distene_blsurf_data_set_sizemap_iso_cad_edge meshgems_cadsurf_data_set_sizemap_iso_cad_edge
#define distene_blsurf_data_set_sizemap_iso_cad_point meshgems_cadsurf_data_set_sizemap_iso_cad_point
#define distene_blsurf_data_set_sizemap meshgems_cadsurf_data_set_sizemap
#define distene_blsurf_compute_mesh meshgems_cadsurf_compute_mesh
#define distene_blsurf_data_get_mesh meshgems_cadsurf_data_get_mesh
#define distene_blsurf_data_regain_mesh meshgems_cadsurf_data_regain_mesh
#define distene_blsurf_get_vertex_location_on_edge_count meshgems_cadsurf_get_vertex_location_on_edge_count
#define distene_blsurf_get_vertex_location_on_edge meshgems_cadsurf_get_vertex_location_on_edge
#define distene_blsurf_get_vertex_location_on_face_count meshgems_cadsurf_get_vertex_location_on_face_count
#define distene_blsurf_get_vertex_location_on_face meshgems_cadsurf_get_vertex_location_on_face
#define distene_blsurf_print_ident meshgems_cadsurf_print_ident
#define distene_blsurf_session_t meshgems_cadsurf_session_t
#define DISTENE_BLSURF_BASE MESHGEMS_CADSURF_BASE
#define DISTENE_BLSURF_ERROR(x_) MESHGEMS_CADSURF_ERROR(x_)
#define DISTENE_BLSURF_WARNING(x_) MESHGEMS_CADSURF_WARNING(x_)
#define DISTENE_BLSURF_CODE(x_) MESHGEMS_CADSURF_CODE(x_)

#define blsurf_session_new meshgems_cadsurf_session_new
#define blsurf_session_delete meshgems_cadsurf_session_delete
#define blsurf_set_param meshgems_cadsurf_set_param
#define blsurf_get_param meshgems_cadsurf_get_param
#define blsurf_set_message_callback meshgems_cadsurf_set_message_callback
#define blsurf_set_interrupt_callback meshgems_cadsurf_set_interrupt_callback
#define blsurf_data_set_cad meshgems_cadsurf_data_set_cad
#define blsurf_data_set_dcad meshgems_cadsurf_data_set_dcad
#define blsurf_data_set_sizemap_iso_cad_face meshgems_cadsurf_data_set_sizemap_iso_cad_face
#define blsurf_data_set_sizemap_iso_cad_edge meshgems_cadsurf_data_set_sizemap_iso_cad_edge
#define blsurf_data_set_sizemap_iso_cad_point meshgems_cadsurf_data_set_sizemap_iso_cad_point
#define blsurf_data_set_sizemap meshgems_cadsurf_data_set_sizemap
#define blsurf_compute_mesh meshgems_cadsurf_compute_mesh
#define blsurf_data_get_mesh meshgems_cadsurf_data_get_mesh
#define blsurf_data_regain_mesh meshgems_cadsurf_data_regain_mesh
#define blsurf_get_vertex_location_on_edge_count meshgems_cadsurf_get_vertex_location_on_edge_count
#define blsurf_get_vertex_location_on_edge meshgems_cadsurf_get_vertex_location_on_edge
#define blsurf_get_vertex_location_on_face_count meshgems_cadsurf_get_vertex_location_on_face_count
#define blsurf_get_vertex_location_on_face meshgems_cadsurf_get_vertex_location_on_face
#define blsurf_print_ident meshgems_cadsurf_print_ident
#define blsurf_session_t meshgems_cadsurf_session_t
#define BLSURF_BASE MESHGEMS_CADSURF_BASE
#define BLSURF_ERROR(x_) MESHGEMS_CADSURF_ERROR(x_)
#define BLSURF_WARNING(x_) MESHGEMS_CADSURF_WARNING(x_)
#define BLSURF_CODE(x_) MESHGEMS_CADSURF_CODE(x_)



#endif // MESHGEMS_NO_OLD_NAMES
#endif // __MESHGEMS_CADSURF_OLD_NAMES__

