#ifndef __MESHGEMS_CADSURF_SHORT_NAMES__
#define __MESHGEMS_CADSURF_SHORT_NAMES__

// COPYRIGHT DASSAULT SYSTEMES 2022
//=============================================================================
/**
 * @CAA2Level L0
 * @CAA2Usage U0
 */
/**
 * Short names. Allow the caller to omit the meshgems_ prefix.
 */

#ifndef MESHGEMS_NO_SHORT_NAMES
#define cadsurf_calloc_generic_buffer meshgems_cadsurf_calloc_generic_buffer
#define cadsurf_compute_mesh meshgems_cadsurf_compute_mesh
#define cadsurf_data_get_mesh meshgems_cadsurf_data_get_mesh
#define cadsurf_data_regain_mesh meshgems_cadsurf_data_regain_mesh
#define cadsurf_data_set_cad meshgems_cadsurf_data_set_cad
#define cadsurf_data_set_dcad meshgems_cadsurf_data_set_dcad
#define cadsurf_data_set_sizemap meshgems_cadsurf_data_set_sizemap
#define cadsurf_data_set_sizemap_iso_cad_edge meshgems_cadsurf_data_set_sizemap_iso_cad_edge
#define cadsurf_data_set_sizemap_iso_cad_face meshgems_cadsurf_data_set_sizemap_iso_cad_face
#define cadsurf_data_set_sizemap_iso_cad_point meshgems_cadsurf_data_set_sizemap_iso_cad_point
#define cadsurf_free_generic_buffer meshgems_cadsurf_free_generic_buffer
#define cadsurf_get_edge_location_on_edge_count meshgems_cadsurf_get_edge_location_on_edge_count
#define cadsurf_get_edge_location_on_edge_extended meshgems_cadsurf_get_edge_location_on_edge_extended
#define cadsurf_get_intersecting_edge meshgems_cadsurf_get_intersecting_edge
#define cadsurf_get_intersecting_edge_count meshgems_cadsurf_get_intersecting_edge_count
#define cadsurf_get_intersecting_face meshgems_cadsurf_get_intersecting_face
#define cadsurf_get_intersecting_face_count meshgems_cadsurf_get_intersecting_face_count
#define cadsurf_get_mesh meshgems_cadsurf_get_mesh
#define cadsurf_get_param meshgems_cadsurf_get_param
#define cadsurf_get_quadrilateral_location_on_face meshgems_cadsurf_get_quadrilateral_location_on_face
#define cadsurf_get_quadrilateral_location_on_face_extended meshgems_cadsurf_get_quadrilateral_location_on_face_extended
#define cadsurf_get_sizemap meshgems_cadsurf_get_sizemap
#define cadsurf_get_triangle_location_on_face meshgems_cadsurf_get_triangle_location_on_face
#define cadsurf_get_triangle_location_on_face_extended meshgems_cadsurf_get_triangle_location_on_face_extended
#define cadsurf_get_version_ident_string meshgems_cadsurf_get_version_ident_string
#define cadsurf_get_version_major meshgems_cadsurf_get_version_major
#define cadsurf_get_version_minor meshgems_cadsurf_get_version_minor
#define cadsurf_get_version_patch meshgems_cadsurf_get_version_patch
#define cadsurf_get_version_string meshgems_cadsurf_get_version_string
#define cadsurf_get_vertex_location_on_discrete_edge meshgems_cadsurf_get_vertex_location_on_discrete_edge
#define cadsurf_get_vertex_location_on_discrete_edge_count meshgems_cadsurf_get_vertex_location_on_discrete_edge_count
#define cadsurf_get_vertex_location_on_discrete_face meshgems_cadsurf_get_vertex_location_on_discrete_face
#define cadsurf_get_vertex_location_on_discrete_face_count meshgems_cadsurf_get_vertex_location_on_discrete_face_count
#define cadsurf_get_vertex_location_on_discrete_wire meshgems_cadsurf_get_vertex_location_on_discrete_wire
#define cadsurf_get_vertex_location_on_discrete_wire_count meshgems_cadsurf_get_vertex_location_on_discrete_wire_count
#define cadsurf_get_vertex_location_on_edge meshgems_cadsurf_get_vertex_location_on_edge
#define cadsurf_get_vertex_location_on_edge_count meshgems_cadsurf_get_vertex_location_on_edge_count
#define cadsurf_get_vertex_location_on_face meshgems_cadsurf_get_vertex_location_on_face
#define cadsurf_get_vertex_location_on_face_count meshgems_cadsurf_get_vertex_location_on_face_count
#define cadsurf_get_vertex_location_on_vertex meshgems_cadsurf_get_vertex_location_on_vertex
#define cadsurf_get_vertex_location_on_vertex_count meshgems_cadsurf_get_vertex_location_on_vertex_count
#define cadsurf_get_vertex_location_on_wire meshgems_cadsurf_get_vertex_location_on_wire
#define cadsurf_get_vertex_location_on_wire_count meshgems_cadsurf_get_vertex_location_on_wire_count
#define cadsurf_get_vertex_size_aniso meshgems_cadsurf_get_vertex_size_aniso
#define cadsurf_get_vertex_size_iso meshgems_cadsurf_get_vertex_size_iso
#define cadsurf_regain_mesh meshgems_cadsurf_regain_mesh
#define cadsurf_session_delete meshgems_cadsurf_session_delete
#define cadsurf_session_new meshgems_cadsurf_session_new
#define cadsurf_session_set_banner meshgems_cadsurf_session_set_banner
#define cadsurf_set_cad meshgems_cadsurf_set_cad
#define cadsurf_set_dcad meshgems_cadsurf_set_dcad
#define cadsurf_set_element_generation_map meshgems_cadsurf_set_element_generation_map
#define cadsurf_set_interrupt_callback meshgems_cadsurf_set_interrupt_callback
#define cadsurf_set_mesh meshgems_cadsurf_set_mesh
#define cadsurf_set_message_callback meshgems_cadsurf_set_message_callback
#define cadsurf_set_param meshgems_cadsurf_set_param
#define cadsurf_set_sizemap meshgems_cadsurf_set_sizemap
#define cadsurf_set_sizemap_iso_cad_edge meshgems_cadsurf_set_sizemap_iso_cad_edge
#define cadsurf_set_sizemap_iso_cad_face meshgems_cadsurf_set_sizemap_iso_cad_face
#define cadsurf_set_sizemap_iso_cad_point meshgems_cadsurf_set_sizemap_iso_cad_point
#define cadsurf_set_start_thread_callback meshgems_cadsurf_set_start_thread_callback
#define cadsurf_set_stop_thread_callback meshgems_cadsurf_set_stop_thread_callback
#define cadsurf_session_t meshgems_cadsurf_session_t
#define cadsurf_update_mesh meshgems_cadsurf_update_mesh
#define cadsurf_update_sizemap meshgems_cadsurf_update_sizemap
#define CADSURF_ERROR(x_) MESHGEMS_CADSURF_ERROR(x_)
#define CADSURF_WARNING(x_) MESHGEMS_CADSURF_WARNING(x_)
#endif /* MESHGEMS_NO_SHORT_NAMES */
#endif /* __MESHGEMS_CADSURF_SHORT_NAMES__ */
