#ifndef __MESHGEMS_CLEANER_SHORT_NAMES__
#define __MESHGEMS_CLEANER_SHORT_NAMES__

/**
 * Short names. Allow the caller to omit the meshgems_ prefix.
 */

#ifndef MESHGEMS_NO_SHORT_NAMES
#define cleaner_check meshgems_cleaner_check
#define cleaner_fix meshgems_cleaner_fix
#define cleaner_get_manifold_shell_count meshgems_cleaner_get_manifold_shell_count
#define cleaner_get_manifold_shell_mesh meshgems_cleaner_get_manifold_shell_mesh
#define cleaner_get_mesh meshgems_cleaner_get_mesh
#define cleaner_get_result_element_area meshgems_cleaner_get_result_element_area
#define cleaner_get_result_element_vertex_coordinates_on_input meshgems_cleaner_get_result_element_vertex_coordinates_on_input
#define cleaner_get_result_element_vertex_coordinates_on_projected meshgems_cleaner_get_result_element_vertex_coordinates_on_projected
#define cleaner_get_shell_group_count meshgems_cleaner_get_shell_group_count
#define cleaner_get_shell_group_mesh meshgems_cleaner_get_shell_group_mesh
#define cleaner_get_sizemap meshgems_cleaner_get_sizemap
#define cleaner_get_version_ident_string meshgems_cleaner_get_version_ident_string
#define cleaner_get_version_major meshgems_cleaner_get_version_major
#define cleaner_get_version_minor meshgems_cleaner_get_version_minor
#define cleaner_get_version_patch meshgems_cleaner_get_version_patch
#define cleaner_get_version_string meshgems_cleaner_get_version_string
#define cleaner_mesh_get_BadShape meshgems_cleaner_mesh_get_BadShape
#define cleaner_mesh_get_BadShape_count meshgems_cleaner_mesh_get_BadShape_count
#define cleaner_mesh_get_FreeEdge meshgems_cleaner_mesh_get_FreeEdge
#define cleaner_mesh_get_FreeEdge_count meshgems_cleaner_mesh_get_FreeEdge_count
#define cleaner_mesh_get_Inter meshgems_cleaner_mesh_get_Inter
#define cleaner_mesh_get_Inter_1d_array meshgems_cleaner_mesh_get_Inter_1d_array
#define cleaner_mesh_get_Inter_1d_count meshgems_cleaner_mesh_get_Inter_1d_count
#define cleaner_mesh_get_Inter_count meshgems_cleaner_mesh_get_Inter_count
#define cleaner_mesh_get_MultipleEdge meshgems_cleaner_mesh_get_MultipleEdge
#define cleaner_mesh_get_MultipleEdge_count meshgems_cleaner_mesh_get_MultipleEdge_count
#define cleaner_mesh_get_NearTri meshgems_cleaner_mesh_get_NearTri
#define cleaner_mesh_get_NearTri_count meshgems_cleaner_mesh_get_NearTri_count
#define cleaner_mesh_get_Overlap meshgems_cleaner_mesh_get_Overlap
#define cleaner_mesh_get_Overlap_count meshgems_cleaner_mesh_get_Overlap_count
#define cleaner_mesh_get_PointFixable_array meshgems_cleaner_mesh_get_PointFixable_array
#define cleaner_mesh_get_PointFixable_count meshgems_cleaner_mesh_get_PointFixable_count
#define cleaner_mesh_get_SmallTri meshgems_cleaner_mesh_get_SmallTri
#define cleaner_mesh_get_SmallTri_count meshgems_cleaner_mesh_get_SmallTri_count
#define cleaner_project_mesh_on_surface meshgems_cleaner_project_mesh_on_surface
#define cleaner_regain_mesh meshgems_cleaner_regain_mesh
#define cleaner_session_delete meshgems_cleaner_session_delete
#define cleaner_session_mesh_write_extended_file meshgems_cleaner_session_mesh_write_extended_file
#define cleaner_session_new meshgems_cleaner_session_new
#define cleaner_session_set_banner meshgems_cleaner_session_set_banner
#define cleaner_set_interrupt_callback meshgems_cleaner_set_interrupt_callback
#define cleaner_set_message_callback meshgems_cleaner_set_message_callback
#define cleaner_set_param meshgems_cleaner_set_param
#define cleaner_set_sizemap meshgems_cleaner_set_sizemap
#define cleaner_set_surface_mesh meshgems_cleaner_set_surface_mesh
#define cleaner_session_t meshgems_cleaner_session_t
#define cleaner_unlock_product meshgems_cleaner_unlock_product
#endif /* MESHGEMS_NO_SHORT_NAMES */
#endif /* __MESHGEMS_CLEANER_SHORT_NAMES__ */
