#ifndef __MESHGEMS_HEXA_SHORT_NAMES__
#define __MESHGEMS_HEXA_SHORT_NAMES__

/**
 * Short names. Allow the caller to omit the meshgems_ prefix.
 */

#ifndef MESHGEMS_NO_SHORT_NAMES
#define hexa_compute_mesh meshgems_hexa_compute_mesh
#define hexa_compute_volume_mesh meshgems_hexa_compute_volume_mesh
#define hexa_get_boundary_layer_vertex_count meshgems_hexa_get_boundary_layer_vertex_count
#define hexa_get_boundary_layer_vertex_information meshgems_hexa_get_boundary_layer_vertex_information
#define hexa_get_coarse_hexahedron_count meshgems_hexa_get_coarse_hexahedron_count
#define hexa_get_coarse_hexahedron_list meshgems_hexa_get_coarse_hexahedron_list
#define hexa_get_mesh meshgems_hexa_get_mesh
#define hexa_get_version_ident_string meshgems_hexa_get_version_ident_string
#define hexa_get_version_major meshgems_hexa_get_version_major
#define hexa_get_version_minor meshgems_hexa_get_version_minor
#define hexa_get_version_patch meshgems_hexa_get_version_patch
#define hexa_get_version_string meshgems_hexa_get_version_string
#define hexa_get_vertices_on_geometric_quadrilaterals_count meshgems_hexa_get_vertices_on_geometric_quadrilaterals_count
#define hexa_get_vertices_on_geometric_quadrilaterals_info meshgems_hexa_get_vertices_on_geometric_quadrilaterals_info
#define hexa_get_vertices_on_geometric_triangles_count meshgems_hexa_get_vertices_on_geometric_triangles_count
#define hexa_get_vertices_on_geometric_triangles_info meshgems_hexa_get_vertices_on_geometric_triangles_info
#define hexa_io_count_bytes meshgems_hexa_io_count_bytes
#define hexa_io_tictac meshgems_hexa_io_tictac
#define hexa_regain_mesh meshgems_hexa_regain_mesh
#define hexa_session_delete meshgems_hexa_session_delete
#define hexa_session_new meshgems_hexa_session_new
#define hexa_session_set_banner meshgems_hexa_session_set_banner
#define hexa_set_anisotropic_layer_sizes_alongZ meshgems_hexa_set_anisotropic_layer_sizes_alongZ
#define hexa_set_boundary_layer_parameters_on_tag meshgems_hexa_set_boundary_layer_parameters_on_tag
#define hexa_set_boundary_layers_parameters meshgems_hexa_set_boundary_layers_parameters
#define hexa_set_imprinted_surface_ids meshgems_hexa_set_imprinted_surface_ids
#define hexa_set_interrupt_callback meshgems_hexa_set_interrupt_callback
#define hexa_set_local_level_parameters meshgems_hexa_set_local_level_parameters
#define hexa_set_message_callback meshgems_hexa_set_message_callback
#define hexa_set_param meshgems_hexa_set_param
#define hexa_set_sizemap meshgems_hexa_set_sizemap
#define hexa_set_surface_mesh meshgems_hexa_set_surface_mesh
#define hexa_session_t meshgems_hexa_session_t
#define hexa_unlock_product meshgems_hexa_unlock_product
#endif /* MESHGEMS_NO_SHORT_NAMES */
#endif /* __MESHGEMS_HEXA_SHORT_NAMES__ */
