#ifndef __MESHGEMS_HEXA_OLD_NAMES_H__
#define __MESHGEMS_HEXA_OLD_NAMES_H__

#ifndef MESHGEMS_NO_OLD_NAMES

#define  distene_hexa_session_new meshgems_hexa_session_new
#define  distene_hexa_session_delete meshgems_hexa_session_delete
#define  distene_hexa_set_message_callback  meshgems_hexa_set_message_callback
#define  distene_hexa_set_interrupt_callback meshgems_hexa_set_interrupt_callback
#define  distene_hexa_set_surface_mesh meshgems_hexa_set_surface_mesh
#define  distene_hexa_set_background_mesh meshgems_hexa_set_background_mesh
#define  distene_hexa_set_sizemap meshgems_hexa_set_sizemap
#define  distene_hexa_set_subdomain_from_triangle_seed meshgems_hexa_set_subdomain_from_triangle_seed
#define  distene_hexa_set_subdomain_from_triangle_count meshgems_hexa_set_subdomain_from_triangle_count
#define  distene_hexa_compute_volume_mesh meshgems_hexa_compute_volume_mesh
#define  distene_hexa_get_mesh meshgems_hexa_get_mesh
#define  distene_hexa_get_coarse_hexahedron_count meshgems_hexa_get_coarse_hexahedron_count
#define  distene_hexa_get_coarse_hexahedron_list meshgems_hexa_get_coarse_hexahedron_list
#define  distene_hexa_get_vertices_on_geometric_triangles_count meshgems_hexa_get_vertices_on_geometric_triangles_count
#define  distene_hexa_get_vertices_on_geometric_triangles_info meshgems_hexa_get_vertices_on_geometric_triangles_info
#define  distene_hexa_get_vertices_on_geometric_quadrilaterals_info meshgems_hexa_get_vertices_on_geometric_quadrilaterals_info
#define  distene_hexa_get_vertices_on_geometric_quadrilaterals_count meshgems_hexa_get_vertices_on_geometric_quadrilaterals_count
#define  distene_hexa_regain_mesh meshgems_hexa_regain_mesh
#define  distene_hexa_set_param meshgems_hexa_set_param
#define  distene_hexa_set_surface_mesh meshgems_hexa_set_surface_mesh
#define  distene_hexa_set_background_mesh meshgems_hexa_set_background_mesh
#define  distene_hexa_session_t meshgems_hexa_session_t

#endif /* MESHGEMS_NO_OLD_NAMES */
#endif /* __MESHGEMS_HEXA_OLD_NAMES_H_ */
