#ifndef __MESHGEMS_HYBRID_CFD_SHORT_NAMES__
#define __MESHGEMS_HYBRID_CFD_SHORT_NAMES__
// COPYRIGHT DASSAULT SYSTEMES 2022
//=============================================================================
/**
 * @CAA2Level L0
 * @CAA2Usage U0
 */
/**
 * Short names. Allow the caller to omit the meshgems_ prefix.
 */

#ifndef MESHGEMS_NO_SHORT_NAMES
#define hybrid_cfd_get_distance_to_original_surface_sizemap meshgems_hybrid_cfd_get_distance_to_original_surface_sizemap
#define hybrid_cfd_get_distance_to_original_surface_sizemap_abs meshgems_hybrid_cfd_get_distance_to_original_surface_sizemap_abs
#define hybrid_cfd_get_edge_global_count meshgems_hybrid_cfd_get_edge_global_count
#define hybrid_cfd_get_mesh meshgems_hybrid_cfd_get_mesh
#define hybrid_cfd_get_sizemap meshgems_hybrid_cfd_get_sizemap
#define hybrid_cfd_get_subdomain_count meshgems_hybrid_cfd_get_subdomain_count
#define hybrid_cfd_get_subdomain_edges_global_index meshgems_hybrid_cfd_get_subdomain_edges_global_index
#define hybrid_cfd_get_subdomain_edges_global_index_count meshgems_hybrid_cfd_get_subdomain_edges_global_index_count
#define hybrid_cfd_get_subdomain_index meshgems_hybrid_cfd_get_subdomain_index
#define hybrid_cfd_get_subdomain_mesh meshgems_hybrid_cfd_get_subdomain_mesh
#define hybrid_cfd_get_subdomain_sizemap meshgems_hybrid_cfd_get_subdomain_sizemap
#define hybrid_cfd_get_subdomain_tetrahedra_global_index meshgems_hybrid_cfd_get_subdomain_tetrahedra_global_index
#define hybrid_cfd_get_subdomain_tetrahedra_global_index_count meshgems_hybrid_cfd_get_subdomain_tetrahedra_global_index_count
#define hybrid_cfd_get_subdomain_triangles_global_index meshgems_hybrid_cfd_get_subdomain_triangles_global_index
#define hybrid_cfd_get_subdomain_triangles_global_index_count meshgems_hybrid_cfd_get_subdomain_triangles_global_index_count
#define hybrid_cfd_get_subdomain_vertices_global_index meshgems_hybrid_cfd_get_subdomain_vertices_global_index
#define hybrid_cfd_get_subdomain_vertices_global_index_count meshgems_hybrid_cfd_get_subdomain_vertices_global_index_count
#define hybrid_cfd_get_tetrahedron_global_count meshgems_hybrid_cfd_get_tetrahedron_global_count
#define hybrid_cfd_get_triangle_global_count meshgems_hybrid_cfd_get_triangle_global_count
#define hybrid_cfd_get_version_ident_string meshgems_hybrid_cfd_get_version_ident_string
#define hybrid_cfd_get_version_major meshgems_hybrid_cfd_get_version_major
#define hybrid_cfd_get_version_minor meshgems_hybrid_cfd_get_version_minor
#define hybrid_cfd_get_version_patch meshgems_hybrid_cfd_get_version_patch
#define hybrid_cfd_get_version_string meshgems_hybrid_cfd_get_version_string
#define hybrid_cfd_get_vertex_global_count meshgems_hybrid_cfd_get_vertex_global_count
#define hybrid_cfd_mesh meshgems_hybrid_cfd_mesh
#define hybrid_cfd_compute_mesh meshgems_hybrid_cfd_compute_mesh
#define hybrid_cfd_regain_mesh meshgems_hybrid_cfd_regain_mesh
#define hybrid_cfd_regain_sizemap meshgems_hybrid_cfd_regain_sizemap
#define hybrid_cfd_regain_subdomain_mesh meshgems_hybrid_cfd_regain_subdomain_mesh
#define hybrid_cfd_regain_subdomain_sizemap meshgems_hybrid_cfd_regain_subdomain_sizemap
#define hybrid_cfd_session_delete meshgems_hybrid_cfd_session_delete
#define hybrid_cfd_session_new meshgems_hybrid_cfd_session_new
#define hybrid_cfd_set_input_mesh meshgems_hybrid_cfd_set_input_mesh
#define hybrid_cfd_set_interrupt_callback meshgems_hybrid_cfd_set_interrupt_callback
#define hybrid_cfd_set_message_callback meshgems_hybrid_cfd_set_message_callback
#define hybrid_cfd_set_param meshgems_hybrid_cfd_set_param
#define hybrid_cfd_set_sizemap meshgems_hybrid_cfd_set_sizemap
#define hybrid_cfd_set_size_specification meshgems_hybrid_cfd_set_size_specification
#define hybrid_cfd_set_tetrahedron_quality_callback meshgems_hybrid_cfd_set_tetrahedron_quality_callback
#define hybrid_cfd_size_specification_add_boundary_layer_arithmetic_constraint_on_face meshgems_hybrid_cfd_size_specification_add_boundary_layer_arithmetic_constraint_on_face
#define hybrid_cfd_size_specification_add_boundary_layer_arithmetic_constraint_on_face_tag meshgems_hybrid_cfd_size_specification_add_boundary_layer_arithmetic_constraint_on_face_tag
#define hybrid_cfd_size_specification_add_boundary_layer_arithmetic_constraint_on_face_tag_in_subdomain meshgems_hybrid_cfd_size_specification_add_boundary_layer_arithmetic_constraint_on_face_tag_in_subdomain
#define hybrid_cfd_size_specification_add_boundary_layer_arithmetic_constraint_on_subdomain meshgems_hybrid_cfd_size_specification_add_boundary_layer_arithmetic_constraint_on_subdomain
#define hybrid_cfd_size_specification_add_boundary_layer_distribution_constraint_on_face meshgems_hybrid_cfd_size_specification_add_boundary_layer_distribution_constraint_on_face
#define hybrid_cfd_size_specification_add_boundary_layer_distribution_constraint_on_face_tag meshgems_hybrid_cfd_size_specification_add_boundary_layer_distribution_constraint_on_face_tag
#define hybrid_cfd_size_specification_add_boundary_layer_distribution_constraint_on_face_tag_in_subdomain meshgems_hybrid_cfd_size_specification_add_boundary_layer_distribution_constraint_on_face_tag_in_subdomain
#define hybrid_cfd_size_specification_add_boundary_layer_distribution_constraint_on_subdomain meshgems_hybrid_cfd_size_specification_add_boundary_layer_distribution_constraint_on_subdomain
#define hybrid_cfd_size_specification_add_boundary_layer_geometric_constraint_on_face meshgems_hybrid_cfd_size_specification_add_boundary_layer_geometric_constraint_on_face
#define hybrid_cfd_size_specification_add_boundary_layer_geometric_constraint_on_face_tag meshgems_hybrid_cfd_size_specification_add_boundary_layer_geometric_constraint_on_face_tag
#define hybrid_cfd_size_specification_add_boundary_layer_geometric_constraint_on_face_tag_in_subdomain meshgems_hybrid_cfd_size_specification_add_boundary_layer_geometric_constraint_on_face_tag_in_subdomain
#define hybrid_cfd_size_specification_add_boundary_layer_geometric_constraint_on_subdomain meshgems_hybrid_cfd_size_specification_add_boundary_layer_geometric_constraint_on_subdomain
#define hybrid_cfd_size_specification_add_boundary_layer_null_constraint_on_face meshgems_hybrid_cfd_size_specification_add_boundary_layer_null_constraint_on_face
#define hybrid_cfd_size_specification_add_boundary_layer_null_constraint_on_face_tag meshgems_hybrid_cfd_size_specification_add_boundary_layer_null_constraint_on_face_tag
#define hybrid_cfd_size_specification_add_boundary_layer_null_constraint_on_face_tag_in_subdomain meshgems_hybrid_cfd_size_specification_add_boundary_layer_null_constraint_on_face_tag_in_subdomain
#define hybrid_cfd_size_specification_add_boundary_layer_null_constraint_on_subdomain meshgems_hybrid_cfd_size_specification_add_boundary_layer_null_constraint_on_subdomain
#define hybrid_cfd_size_specification_add_boundary_layer_uniform_constraint_on_face meshgems_hybrid_cfd_size_specification_add_boundary_layer_uniform_constraint_on_face
#define hybrid_cfd_size_specification_add_boundary_layer_uniform_constraint_on_face_tag meshgems_hybrid_cfd_size_specification_add_boundary_layer_uniform_constraint_on_face_tag
#define hybrid_cfd_size_specification_add_boundary_layer_uniform_constraint_on_face_tag_in_subdomain meshgems_hybrid_cfd_size_specification_add_boundary_layer_uniform_constraint_on_face_tag_in_subdomain
#define hybrid_cfd_size_specification_add_boundary_layer_uniform_constraint_on_subdomain meshgems_hybrid_cfd_size_specification_add_boundary_layer_uniform_constraint_on_subdomain
#define hybrid_cfd_size_specification_delete meshgems_hybrid_cfd_size_specification_delete
#define hybrid_cfd_size_specification_new meshgems_hybrid_cfd_size_specification_new
#define hybrid_cfd_session_t meshgems_hybrid_cfd_session_t
#define hybrid_cfd_size_specification_boundary_layer_distribution_t meshgems_hybrid_cfd_size_specification_boundary_layer_distribution_t
#define hybrid_cfd_size_specification_t meshgems_hybrid_cfd_size_specification_t
#define hybrid_cfd_tetrahedron_quality_callback_t meshgems_hybrid_cfd_tetrahedron_quality_callback_t
#define hybrid_cfd_unlock_product meshgems_hybrid_cfd_unlock_product
#endif /* MESHGEMS_NO_SHORT_NAMES */
#endif /* __MESHGEMS_HYBRID_CFD_SHORT_NAMES__ */
