#ifndef __MESHGEMS_HYBRID_SHORT_NAMES__
#define __MESHGEMS_HYBRID_SHORT_NAMES__

/**
 * Short names. Allow the caller to omit the meshgems_ prefix.
 */

#ifndef MESHGEMS_NO_SHORT_NAMES
#define  meshgems_
#define hybrid_compute_mesh meshgems_hybrid_compute_mesh
#define hybrid_get_boundary_layer_vertex_count meshgems_hybrid_get_boundary_layer_vertex_count
#define hybrid_get_boundary_layer_vertex_information meshgems_hybrid_get_boundary_layer_vertex_information
#define hybrid_get_hexahedron_layer_numbering meshgems_hybrid_get_hexahedron_layer_numbering
#define hybrid_get_hexahedron_layer_surface_tag meshgems_hybrid_get_hexahedron_layer_surface_tag
#define hybrid_get_mesh meshgems_hybrid_get_mesh
#define hybrid_get_prism_layer_numbering meshgems_hybrid_get_prism_layer_numbering
#define hybrid_get_prism_layer_surface_tag meshgems_hybrid_get_prism_layer_surface_tag
#define hybrid_get_pyramid_layer_numbering meshgems_hybrid_get_pyramid_layer_numbering
#define hybrid_get_pyramid_layer_surface_tag meshgems_hybrid_get_pyramid_layer_surface_tag
#define hybrid_get_tetrahedron_layer_numbering meshgems_hybrid_get_tetrahedron_layer_numbering
#define hybrid_get_tetrahedron_layer_surface_tag meshgems_hybrid_get_tetrahedron_layer_surface_tag
#define hybrid_get_version_ident_string meshgems_hybrid_get_version_ident_string
#define hybrid_get_version_major meshgems_hybrid_get_version_major
#define hybrid_get_version_minor meshgems_hybrid_get_version_minor
#define hybrid_get_version_patch meshgems_hybrid_get_version_patch
#define hybrid_hybrid_version_string meshgems_hybrid_hybrid_version_string
#define hybrid_optimise_volume meshgems_hybrid_optimise_volume
#define hybrid_regain_mesh meshgems_hybrid_regain_mesh
#define hybrid_session_delete meshgems_hybrid_session_delete
#define hybrid_session_new meshgems_hybrid_session_new
#define hybrid_session_set_banner meshgems_hybrid_session_set_banner
#define hybrid_set_boundary_layer_imprinting_tag meshgems_hybrid_set_boundary_layer_imprinting_tag
#define hybrid_set_boundary_layers_height meshgems_hybrid_set_boundary_layers_height
#define hybrid_set_boundary_layers_imprint_id meshgems_hybrid_set_boundary_layers_imprint_id
#define hybrid_set_boundary_layers_imprint_tags meshgems_hybrid_set_boundary_layers_imprint_tags
#define hybrid_set_boundary_layer_snapping_tag meshgems_hybrid_set_boundary_layer_snapping_tag
#define hybrid_set_boundary_layers_parameter_onref meshgems_hybrid_set_boundary_layers_parameter_onref
#define hybrid_set_boundary_layers_surface_id meshgems_hybrid_set_boundary_layers_surface_id
#define hybrid_set_initial_height_on_surface_tag meshgems_hybrid_set_initial_height_on_surface_tag
#define hybrid_set_interrupt_callback meshgems_hybrid_set_interrupt_callback
#define hybrid_set_message_callback meshgems_hybrid_set_message_callback
#define hybrid_set_param meshgems_hybrid_set_param
#define hybrid_set_sizemap meshgems_hybrid_set_sizemap
#define hybrid_set_surface_mesh meshgems_hybrid_set_surface_mesh
#define hybrid_set_volume_mesh meshgems_hybrid_set_volume_mesh
#define boundary_layer_height_t meshgems_boundary_layer_height_t
#define hybrid_session_t meshgems_hybrid_session_t
#define hybrid_unlock_product meshgems_hybrid_unlock_product
#endif /* MESHGEMS_NO_SHORT_NAMES */
#endif /* __MESHGEMS_HYBRID_SHORT_NAMES__ */
