#ifndef __MESHGEMS_TETRA_HPC_SHORT_NAMES__
#define __MESHGEMS_TETRA_HPC_SHORT_NAMES__
// COPYRIGHT DASSAULT SYSTEMES 2022
//=============================================================================
/**
 * @CAA2Level L0
 * @CAA2Usage U0
 */
/**
 * Short names. Allow the caller to omit the meshgems_ prefix.
 */

#ifndef MESHGEMS_NO_SHORT_NAMES
#define tetra_hpc_get_distance_to_original_surface_sizemap meshgems_tetra_hpc_get_distance_to_original_surface_sizemap
#define tetra_hpc_get_distance_to_original_surface_sizemap_abs meshgems_tetra_hpc_get_distance_to_original_surface_sizemap_abs
#define tetra_hpc_get_edge_global_count meshgems_tetra_hpc_get_edge_global_count
#define tetra_hpc_get_mesh meshgems_tetra_hpc_get_mesh
#define tetra_hpc_get_sizemap meshgems_tetra_hpc_get_sizemap
#define tetra_hpc_get_subdomain_count meshgems_tetra_hpc_get_subdomain_count
#define tetra_hpc_get_subdomain_edges_global_index meshgems_tetra_hpc_get_subdomain_edges_global_index
#define tetra_hpc_get_subdomain_edges_global_index_count meshgems_tetra_hpc_get_subdomain_edges_global_index_count
#define tetra_hpc_get_subdomain_index meshgems_tetra_hpc_get_subdomain_index
#define tetra_hpc_get_subdomain_mesh meshgems_tetra_hpc_get_subdomain_mesh
#define tetra_hpc_get_subdomain_sizemap meshgems_tetra_hpc_get_subdomain_sizemap
#define tetra_hpc_get_subdomain_tetrahedra_global_index meshgems_tetra_hpc_get_subdomain_tetrahedra_global_index
#define tetra_hpc_get_subdomain_tetrahedra_global_index_count meshgems_tetra_hpc_get_subdomain_tetrahedra_global_index_count
#define tetra_hpc_get_subdomain_triangles_global_index meshgems_tetra_hpc_get_subdomain_triangles_global_index
#define tetra_hpc_get_subdomain_triangles_global_index_count meshgems_tetra_hpc_get_subdomain_triangles_global_index_count
#define tetra_hpc_get_subdomain_vertices_global_index meshgems_tetra_hpc_get_subdomain_vertices_global_index
#define tetra_hpc_get_subdomain_vertices_global_index_count meshgems_tetra_hpc_get_subdomain_vertices_global_index_count
#define tetra_hpc_get_tetrahedron_global_count meshgems_tetra_hpc_get_tetrahedron_global_count
#define tetra_hpc_get_triangle_global_count meshgems_tetra_hpc_get_triangle_global_count
#define tetra_hpc_get_version_ident_string meshgems_tetra_hpc_get_version_ident_string
#define tetra_hpc_get_version_major meshgems_tetra_hpc_get_version_major
#define tetra_hpc_get_version_minor meshgems_tetra_hpc_get_version_minor
#define tetra_hpc_get_version_patch meshgems_tetra_hpc_get_version_patch
#define tetra_hpc_get_version_string meshgems_tetra_hpc_get_version_string
#define tetra_hpc_get_vertex_global_count meshgems_tetra_hpc_get_vertex_global_count
#define tetra_hpc_mesh meshgems_tetra_hpc_mesh
#define tetra_hpc_compute_mesh meshgems_tetra_hpc_compute_mesh
#define tetra_hpc_regain_mesh meshgems_tetra_hpc_regain_mesh
#define tetra_hpc_regain_sizemap meshgems_tetra_hpc_regain_sizemap
#define tetra_hpc_regain_subdomain_mesh meshgems_tetra_hpc_regain_subdomain_mesh
#define tetra_hpc_regain_subdomain_sizemap meshgems_tetra_hpc_regain_subdomain_sizemap
#define tetra_hpc_session_delete meshgems_tetra_hpc_session_delete
#define tetra_hpc_session_new meshgems_tetra_hpc_session_new
#define tetra_hpc_set_input_mesh meshgems_tetra_hpc_set_input_mesh
#define tetra_hpc_set_interrupt_callback meshgems_tetra_hpc_set_interrupt_callback
#define tetra_hpc_set_message_callback meshgems_tetra_hpc_set_message_callback
#define tetra_hpc_set_param meshgems_tetra_hpc_set_param
#define tetra_hpc_set_sizemap meshgems_tetra_hpc_set_sizemap
#define tetra_hpc_set_tetrahedron_quality_callback meshgems_tetra_hpc_set_tetrahedron_quality_callback
#define tetra_hpc_session_t meshgems_tetra_hpc_session_t
#define tetra_hpc_tetrahedron_quality_callback_t meshgems_tetra_hpc_tetrahedron_quality_callback_t
#define tetra_hpc_unlock_product meshgems_tetra_hpc_unlock_product
#endif /* MESHGEMS_NO_SHORT_NAMES */
#endif /* __MESHGEMS_TETRA_HPC_SHORT_NAMES__ */
